-- Pack semilla Madrid: proyectos creados por appoyomutuo@gmail.com
-- Requisito: ese usuario debe existir ya en Auth (haber iniciado sesion al menos una vez).
-- Idempotente: ON CONFLICT DO NOTHING

do $$
declare
  owner_id uuid;
begin
  select id into owner_id from auth.users where email = 'appoyomutuo@gmail.com' limit 1;
  if owner_id is null then
    raise exception 'No existe el usuario appoyomutuo@gmail.com. Entra una vez con Google/email y vuelve a ejecutar este SQL.';
  end if;

  insert into public.profiles (id, full_name, bio, neighborhood)
  values (
    owner_id,
    'Appoyo Mutuo',
    'Cuenta oficial con proyectos semilla en Madrid.',
    'Madrid'
  )
  on conflict (id) do update set
    full_name = coalesce(nullif(public.profiles.full_name, ''), excluded.full_name);

  insert into public.projects (
    id, title, description, area, location, neighborhood, address, lat, lng,
    contribution_type, status, people_needed, people_joined, image_url, info_pdf_url,
    conditions, what_happens, what_needed, template_name, created_by, created_at
  ) values
  ('a0000000-0000-4000-8000-000000000101', 'Compra colectiva directa a agricultores', '30 hogares compran juntos a productores de la comarca.

Los participantes se comprometen a comprar una cantidad aproximada cada semana o mes. Al alcanzar volumen suficiente, un pequeño productor puede ofrecer mejores condiciones y organizar un reparto conjunto.', 'subsistencia', 'Mercado de San Fernando, Lavapiés, Madrid', 'Lavapiés', 'Calle de Embajadores 41', 40.4082, -3.7031, 'dinero', 'buscando', 30, 0, '', '', 'Compromiso de compra semanal o mensual y un punto de reparto acordado', 'Pedidos agrupados a productores locales, precios más justos y reparto en el barrio', 'Dinero para pedidos, compromiso de compra y, si hace falta, un espacio para el reparto', 'Compra colectiva', owner_id, '2026-08-01T10:00:00.000Z'),
  ('a0000000-0000-4000-8000-000000000102', 'Cocina comunitaria compartida', 'Una cocina para 15 familias que quieren cocinar en grupo.

Alquilar o recuperar un espacio equipado y compartirlo por turnos para cocinar, preparar conservas, hacer pan y otras elaboraciones colectivas.', 'subsistencia', 'Calle de Embajadores 40, Lavapiés, Madrid', 'Lavapiés', 'Calle de Embajadores 40', 40.4068, -3.7028, 'espacio', 'buscando', 15, 0, '', '', 'Local con cocina usable y calendario de turnos acordado entre las familias', 'Turnos de cocina compartida, elaboraciones colectivas y menos dependencia de comida industrial', 'Dinero para el local, tiempo de cocina y algo de equipamiento', 'Cocina comunitaria', owner_id, '2026-08-01T10:05:00.000Z'),
  ('a0000000-0000-4000-8000-000000000103', 'Red de aprovechamiento alimentario', 'Comida que sobra, comida que se aprovecha.

Comercios, restaurantes, productores y vecinos coordinan excedentes para evitar desperdicio y destinarlos a personas o iniciativas que puedan utilizarlos.', 'subsistencia', 'Mercado de Vallecas, Madrid', 'Vallecas', 'Avenida de la Albufera 42', 40.3935, -3.662, 'tiempo', 'buscando', 20, 0, '', '', 'Al menos varios comercios colaboradores y un equipo estable de recogida', 'Circuitos locales de aprovechamiento y menos comida tirada en el barrio', 'Alimentos, transporte, tiempo de logística y espacios de almacenamiento o cocina', 'Aprovechamiento alimentario', owner_id, '2026-08-01T10:10:00.000Z'),
  ('a0000000-0000-4000-8000-000000000104', 'Grupo para vivienda cooperativa', '10 personas buscando crear una vivienda cooperativa.

Empiezan juntas: encontrar terreno o inmueble, estudiar modelos existentes, financiación y condiciones. No hace falta tener la vivienda desde el principio.', 'vivienda', 'Calle del Espíritu Santo 8, Malasaña, Madrid', 'Malasaña', 'Calle del Espíritu Santo 8', 40.4255, -3.7072, 'dinero', 'buscando', 10, 0, '', '', 'Grupo estable y un plan compartido de búsqueda y aportaciones', 'Camino conjunto hacia una vivienda en régimen cooperativo no especulativo', 'Dinero inicial, conocimientos técnicos o jurídicos, tiempo de búsqueda y organización', 'Vivienda cooperativa', owner_id, '2026-08-01T10:15:00.000Z'),
  ('a0000000-0000-4000-8000-000000000105', 'Banco de herramientas y equipamiento del barrio', '100 vecinos comparten herramientas en lugar de comprarlas.

Taladros, escaleras, herramientas de jardinería, máquinas de limpieza… Una persona necesita un taladro dos veces al año; no tiene sentido que cien personas tengan uno.', 'vivienda', 'Calle de la Palma 45, Malasaña, Madrid', 'Malasaña', 'Calle de la Palma 45', 40.4262, -3.7058, 'espacio', 'buscando', 100, 0, '', '', 'Un local o trastero de custodia y un sistema sencillo de préstamo', 'Préstamo vecinal de herramientas y menos compras individuales innecesarias', 'Herramientas aportadas, un espacio de guardado y personas que gestionen turnos', 'Banco de herramientas', owner_id, '2026-08-01T10:20:00.000Z'),
  ('a0000000-0000-4000-8000-000000000106', 'Rehabilitación colectiva de un edificio', 'Vecinos que se organizan para rehabilitar su edificio.

Coordinan presupuestos, profesionales, compras conjuntas y trabajos de mantenimiento para abaratar y hacer viable lo que en solitario se atasca.', 'vivienda', 'Calle de General Ricardos 122, Carabanchel, Madrid', 'Carabanchel', 'Calle de General Ricardos 122', 40.3885, -3.7245, 'dinero', 'buscando', 12, 0, '', '', 'Mayoría de vecinos interesados y un plan de obras acordado', 'Obras y mantenimiento compartidos, con compras y contratos más asequibles', 'Dinero, conocimientos de obra o mediación, y mucha coordinación', 'Rehabilitación colectiva', owner_id, '2026-08-01T10:25:00.000Z'),
  ('a0000000-0000-4000-8000-000000000107', 'Cooperativa local de reparto', 'Reparto de proximidad gestionado por repartidores.

Pequeños comercios que no pueden permitirse un sistema propio se agrupan para contratar o crear un servicio local de reparto: comercios con necesidad → personas → proyecto → empleo cercano.', 'trabajo', 'Calle de Embajadores 120, Arganzuela, Madrid', 'Arganzuela', 'Calle de Embajadores 120', 40.4005, -3.6985, 'tiempo', 'buscando', 8, 0, '', '', 'Varios comercios adheridos y un núcleo mínimo de repartidoras/es', 'Servicio de reparto de proximidad y posibles puestos de trabajo locales', 'Comercios con demanda, personas dispuestas a repartir, vehículos o bicis y organización', 'Reparto cooperativo', owner_id, '2026-08-01T10:30:00.000Z'),
  ('a0000000-0000-4000-8000-000000000108', 'Red de profesionales para trabajos compartidos', 'Profesionales independientes que quieren trabajar juntos.

Fontaneros, electricistas, carpinteros, diseñadores, informáticos… pueden crear una red para aceptar encargos mayores, compartir herramientas y recomendarse clientes. No hace falta convertirse de inmediato en cooperativa.', 'trabajo', 'Calle de Fuencarral 90, Chamberí, Madrid', 'Chamberí', 'Calle de Fuencarral 90', 40.434, -3.703, 'conocimiento', 'buscando', 15, 0, '', '', 'Acuerdo básico de recomendaciones, tarifas orientativas y resolución de conflictos', 'Encargos compartidos, más capacidad de respuesta y red de confianza profesional', 'Oficios diversos, herramientas compartibles y tiempo de coordinación', 'Red profesional', owner_id, '2026-08-01T10:35:00.000Z'),
  ('a0000000-0000-4000-8000-000000000109', 'Taller cooperativo de reparación', 'Abrimos un taller de reparación gestionado por sus trabajadores.

Electrodomésticos, bicicletas, muebles, pequeños aparatos… Puede empezar buscando 4 personas con conocimientos, un local, herramientas y unos 50 clientes iniciales. Cuando se alcanzan las condiciones, se activa.', 'trabajo', 'Calle de Bravo Murillo 180, Tetuán, Madrid', 'Tetuán', 'Calle de Bravo Murillo 180', 40.4605, -3.6982, 'conocimiento', 'idea', 4, 0, '', '', '4 personas con oficio, local, herramientas básicas y demanda inicial suficiente', 'Taller abierto de reparación con empleo y servicio útil al barrio', 'Conocimientos técnicos, local, herramientas y primeras clientas/es', 'Taller de reparación', owner_id, '2026-08-01T10:40:00.000Z'),
  ('a0000000-0000-4000-8000-000000000110', 'Red vecinal de acompañamiento a mayores', '20 vecinos para que nadie del barrio pase días solo.

Acompañamiento, compras, paseos, pequeñas gestiones o simplemente compañía. El beneficio no tiene por qué ser monetario: es apoyo mutuo en lo cotidiano.', 'cuidados', 'Plaza de Lavapiés, Madrid', 'Lavapiés', 'Plaza de Lavapiés', 40.4089, -3.7015, 'tiempo', 'buscando', 20, 0, '', '', 'Grupo estable, turnos claros y formación básica de acompañamiento', 'Mayores del barrio con compañía y gestiones cubiertas de forma vecinal', 'Sobre todo tiempo, y un espacio de reunión ocasional', 'Red de cuidados', owner_id, '2026-08-01T10:45:00.000Z'),
  ('a0000000-0000-4000-8000-000000000111', 'Red de cuidado infantil compartido', '10 familias organizan turnos de apoyo para sus hijos.

Se coordinan para cubrir momentos concretos: recogidas, tardes, actividades… Importante: no sustituye guarderías ni empleo regulado; es colaboración familiar entre pares, con reglas claras.', 'cuidados', 'Calle de Puerto del Escudo 3, Vallecas, Madrid', 'Vallecas', 'Calle de Puerto del Escudo 3', 40.388, -3.65, 'tiempo', 'buscando', 10, 0, '', '', 'Familias de acuerdo en normas, turnos y límites de lo que se cubre', 'Apoyo mutuo en recogidas y ratos concretos entre familias del barrio', 'Tiempo, organización y algo de conocimiento en cuidados infantiles', 'Cuidado infantil compartido', owner_id, '2026-08-01T10:50:00.000Z'),
  ('a0000000-0000-4000-8000-000000000112', 'Red de apoyo para personas dependientes', 'Una red de ayuda para pequeñas tareas cotidianas.

Compras, gestiones, desplazamientos o tareas domésticas puntuales. No sustituye cuidados profesionales: cubre pequeños huecos que hoy quedan sin atender.', 'cuidados', 'Calle de Alcalá 280, Ciudad Lineal, Madrid', 'Ciudad Lineal', 'Calle de Alcalá 280', 40.4355, -3.65, 'tiempo', 'buscando', 16, 0, '', '', 'Límites claros de qué se ofrece y qué queda fuera (no sustituye profesionales)', 'Pequeñas ayudas cotidianas cubiertas por la red vecinal', 'Tiempo disponible y coordinación sencilla de peticiones', 'Apoyo a dependientes', owner_id, '2026-08-01T10:55:00.000Z'),
  ('a0000000-0000-4000-8000-000000000113', 'Intercambio de conocimientos', 'Yo te enseño fotografía, tú me enseñas inglés.

Sistema de intercambio de habilidades: aportas horas de lo que sabes y recibes horas de lo que quieres aprender.', 'educacion', 'Calle de Augusto Figueroa 24, Chueca, Madrid', 'Chueca', 'Calle de Augusto Figueroa 24', 40.4228, -3.6975, 'conocimiento', 'buscando', 25, 0, '', '', 'Personas con habilidades para ofrecer y un sistema simple de intercambio de horas', 'Intercambios regulares de aprendizaje entre vecinas y vecinos', 'Tiempo y conocimientos que compartir', 'Intercambio de saberes', owner_id, '2026-08-01T11:00:00.000Z'),
  ('a0000000-0000-4000-8000-000000000114', 'Taller comunitario de habilidades prácticas', 'Aprender a reparar, cocinar, coser y mantener tu casa.

Personas del barrio organizan sesiones periódicas donde comparten conocimientos prácticos útiles para la vida cotidiana.', 'educacion', 'Calle de la Escuadra 5, Lavapiés, Madrid', 'Lavapiés', 'Calle de la Escuadra 5', 40.4092, -3.7002, 'conocimiento', 'buscando', 18, 0, '', '', 'Espacio para talleres y un calendario mínimo de sesiones', 'Talleres abiertos de habilidades prácticas en el barrio', 'Personas que sepan y quieran enseñar, material básico y un local', 'Talleres prácticos', owner_id, '2026-08-01T11:05:00.000Z'),
  ('a0000000-0000-4000-8000-000000000115', 'Red de mentoría entre profesionales', 'Profesionales que ofrecen una hora al mes para ayudar a alguien a empezar.

Programación, contabilidad, agricultura, diseño, fontanería… Quien tiene experiencia acompaña a quien está aprendiendo o montando un proyecto. También puede alimentar otros proyectos de Appoyo Mutuo.', 'educacion', 'Calle de Hortaleza 50, Centro, Madrid', 'Centro', 'Calle de Hortaleza 50', 40.422, -3.6988, 'conocimiento', 'buscando', 20, 0, '', '', 'Mentoras/es disponibles al menos una hora al mes y personas que buscan acompañamiento', 'Acompañamientos puntuales que desbloquean aprendizajes y proyectos', 'Experiencia profesional y disponibilidad mínima mensual', 'Mentoría', owner_id, '2026-08-01T11:10:00.000Z'),
  ('a0000000-0000-4000-8000-000000000116', 'Grupo deportivo comunitario', '30 personas entrenan juntas tres días por semana.

Running, senderismo, ciclismo, calistenia… Sin necesidad de gimnasio. No promete resultados médicos: ofrece constancia y compañía.', 'salud', 'Parque del Retiro, Madrid', 'Retiro', 'Puerta del Ángel Caído', 40.4135, -3.6825, 'tiempo', 'buscando', 30, 0, '', '', 'Horarios fijos y un grupo mínimo estable', 'Entrenamientos regulares al aire libre con gente del barrio', 'Tiempo, ganas y un punto de encuentro', 'Deporte comunitario', owner_id, '2026-08-01T11:15:00.000Z'),
  ('a0000000-0000-4000-8000-000000000117', 'Grupo de hábitos saludables', '12 personas intentando mejorar sus hábitos juntas.

Caminar, cocinar mejor, dormir mejor, reducir sedentarismo… La fuerza está en la estructura social, no en promesas clínicas.', 'salud', 'Parque de Berlin, Chamartín, Madrid', 'Chamartín', 'Avenida de Alberto Alcocer', 40.4508, -3.6765, 'tiempo', 'buscando', 12, 0, '', '', 'Grupo cerrado o semiabierto con reglas de apoyo mutuo (sin consejos médicos)', 'Seguimiento colectivo de hábitos cotidianos más sanos', 'Tiempo y compromiso de quedar con regularidad', 'Hábitos saludables', owner_id, '2026-08-01T11:20:00.000Z'),
  ('a0000000-0000-4000-8000-000000000118', 'Red de acompañamiento y bienestar comunitario', 'Personas que quieren un espacio regular para hablar y escucharse.

Encuentros presenciales con reglas claras de convivencia. No sustituye psicología ni atención sanitaria: es apoyo comunitario.', 'salud', 'Calle de la Cabeza 8, Lavapiés, Madrid', 'Lavapiés', 'Calle de la Cabeza 8', 40.4105, -3.7018, 'tiempo', 'buscando', 14, 0, '', '', 'Espacio adecuado, moderación rotativa y límites explícitos (no es terapia)', 'Círculos regulares de escucha y acompañamiento entre pares', 'Tiempo, un local y acuerdos de cuidado del grupo', 'Bienestar comunitario', owner_id, '2026-08-01T11:25:00.000Z'),
  ('a0000000-0000-4000-8000-000000000119', 'Taller artístico compartido', '15 personas crean juntas un taller de arte.

Alquilan un local, compran materiales colectivamente y lo utilizan por turnos: exactamente el tipo de cosa que sola casi nadie puede permitirse.', 'ocio', 'Calle del Doctor Fourquet 24, Lavapiés, Madrid', 'Lavapiés', 'Calle del Doctor Fourquet 24', 40.4078, -3.6989, 'dinero', 'buscando', 15, 0, '', '', 'Local asequible y grupo suficiente para cubrir alquiler y materiales', 'Taller compartido con turnos y materiales comunes', 'Aportación económica, tiempo de uso y algo de gestión del espacio', 'Taller artístico', owner_id, '2026-08-01T11:30:00.000Z'),
  ('a0000000-0000-4000-8000-000000000120', 'Sala de ensayo y creación musical', '10 músicos buscan un espacio compartido.

Varias personas que individualmente no pueden permitirse un local juntan recursos. A medio plazo puede incorporar grabación, conciertos, clases o eventos.', 'ocio', 'Calle de Embajadores 88, Lavapiés, Madrid', 'Lavapiés', 'Calle de Embajadores 88', 40.4055, -3.7012, 'dinero', 'buscando', 10, 0, '', '', 'Presupuesto compartido de alquiler y normas de uso del espacio', 'Sala de ensayo asequible y, si crece, más actividades musicales', 'Dinero para el local, equipos básicos y turnos de ensayo', 'Sala de ensayo', owner_id, '2026-08-01T11:35:00.000Z'),
  ('a0000000-0000-4000-8000-000000000121', 'Cine comunitario', 'Una proyección abierta al barrio cada viernes.

Hace falta espacio, equipamiento y una programación. Puede ser gratuito, con aportación voluntaria u otro modelo permitido.', 'ocio', 'Plaza de Cascorro, Latina, Madrid', 'Latina', 'Plaza de Cascorro', 40.4108, -3.7075, 'espacio', 'buscando', 12, 0, '', '', 'Espacio con permiso de uso, proyector y equipo mínimo de organización', 'Proyecciones periódicas abiertas al vecindario', 'Espacio, material técnico y personas para programar y montar', 'Cine comunitario', owner_id, '2026-08-01T11:40:00.000Z'),
  ('a0000000-0000-4000-8000-000000000122', 'Asamblea abierta de barrio', 'Un espacio fijo para decidir asuntos comunes del vecindario.

Quien quiera puede proponer temas, escuchar y organizar acciones colectivas sin depender solo de instituciones o chats dispersos.', 'comunidad', 'Plaza de Olavide, Chamberí, Madrid', 'Chamberí', 'Plaza de Olavide', 40.4332, -3.7015, 'tiempo', 'buscando', 25, 0, '', '', 'Lugar regular y un mínimo de personas comprometidas con la facilitación', 'Asambleas periódicas y acciones vecinales coordinadas', 'Tiempo, difusión y un espacio de reunión', 'Asamblea de barrio', owner_id, '2026-08-01T11:45:00.000Z'),
  ('a0000000-0000-4000-8000-000000000123', 'Banco de tiempo vecinal', 'Intercambiamos horas: yo te ayudo con lo mío, tú con lo tuyo.

Un banco de tiempo local para intercambiar favores y saberes sin pasar por el dinero en cada gesto.', 'comunidad', 'Calle de Usera 50, Usera, Madrid', 'Usera', 'Calle de Usera 50', 40.387, -3.71, 'tiempo', 'buscando', 40, 0, '', '', 'Sistema de registro de horas y un grupo mínimo activo', 'Intercambio regular de ayudas entre vecinas y vecinos', 'Tiempo, confianza y una persona o equipo que lleve el registro', 'Banco de tiempo', owner_id, '2026-08-01T11:50:00.000Z'),
  ('a0000000-0000-4000-8000-000000000124', 'Biblioteca de las cosas del barrio', 'Prestamos objetos que casi nadie usa a diario.

Además de herramientas: maletas, tiendas de campaña, sillas de fiesta, proyector… Un inventario común reduce compras y refuerza la red vecinal.', 'comunidad', 'Calle de la Princesa 25, Moncloa, Madrid', 'Moncloa', 'Calle de la Princesa 25', 40.4285, -3.7165, 'espacio', 'buscando', 35, 0, '', '', 'Local o estantería compartida e inventario inicial', 'Préstamo vecinal de objetos poco usados y menos consumo innecesario', 'Objetos aportados, espacio de guardado y turnos de gestión', 'Biblioteca de las cosas', owner_id, '2026-08-01T11:55:00.000Z'),
  ('a0000000-0000-4000-8000-000000000125', 'Red de compra y reparto para personas con movilidad reducida', 'Personas del mismo barrio coordinan compras periódicas de alimentos y medicamentos de venta libre, con rutas compartidas y apoyo vecinal.

Resuelve un problema muy concreto: hacer la compra cuando desplazarse es difícil.', 'subsistencia', 'Calle de Amparo 20, Lavapiés, Madrid', 'Lavapiés', 'Calle de Amparo 20', 40.4091, -3.7005, 'tiempo', 'buscando', 18, 0, '', '', 'Rutas semanales acordadas y personas disponibles para hacer o recibir la compra', 'Compras y pequeños encargos cubiertos con apoyo vecinal para quien tiene movilidad reducida', 'Tiempo para rutas, organización de pedidos y personas que necesitan o ofrecen apoyo', 'Compra asistida', owner_id, '2026-08-02T10:00:00.000Z'),
  ('a0000000-0000-4000-8000-000000000126', 'Conservas y transformación comunitaria de excedentes', 'Un grupo compra o recibe fruta y verdura de temporada que no se puede vender y organiza jornadas para convertirla en conservas, salsas, mermeladas, etc.

Convierte excedente barato o desperdiciado en alimentos útiles.', 'subsistencia', 'Mercado de Maravillas, Tetuán, Madrid', 'Tetuán', 'Calle de Bravo Murillo 122', 40.4528, -3.7015, 'tiempo', 'buscando', 16, 0, '', '', 'Cocina o espacio apto para elaboración y un calendario de jornadas', 'Jornadas de transformación de excedentes en conservas compartidas', 'Excedentes o compra de temporada, tiempo de cocina y recipientes/equipo básico', 'Conservas comunitarias', owner_id, '2026-08-02T10:05:00.000Z'),
  ('a0000000-0000-4000-8000-000000000127', 'Red de intercambio de habitaciones entre generaciones', 'Personas mayores con una habitación disponible y personas jóvenes que buscan alojamiento pueden encontrar un acuerdo de convivencia con condiciones claras.

No es simplemente alquilar una habitación: el proyecto puede incorporar acompañamiento, convivencia y ayuda mutua.', 'vivienda', 'Calle de Gaztambide 30, Chamberí, Madrid', 'Chamberí', 'Calle de Gaztambide 30', 40.4348, -3.7142, 'espacio', 'buscando', 20, 0, '', '', 'Acuerdos escritos de convivencia y límites claros de lo que se espera de cada parte', 'Emparejamientos intergeneracionales con apoyo mutuo y vivienda más accesible', 'Habitaciones disponibles, personas buscando alojamiento y mediación del grupo', 'Convivencia intergeneracional', owner_id, '2026-08-02T10:10:00.000Z'),
  ('a0000000-0000-4000-8000-000000000128', 'Grupo de compra colectiva para rehabilitación energética', '20–50 hogares se organizan para contratar conjuntamente aislamiento, ventanas, placas solares u otras mejoras.

El poder está en juntar demanda suficiente para negociar mejores condiciones.', 'vivienda', 'Calle de Alcalá 150, Salamanca, Madrid', 'Salamanca', 'Calle de Alcalá 150', 40.4245, -3.6785, 'dinero', 'buscando', 35, 0, '', '', 'Número mínimo de hogares interesados y un pliego común de mejoras', 'Contratación conjunta con mejores precios y plazos para rehabilitación energética', 'Hogares comprometidos, aportación económica y coordinación técnica', 'Rehabilitación energética', owner_id, '2026-08-02T10:15:00.000Z'),
  ('a0000000-0000-4000-8000-000000000129', 'Cooperativa de servicios para autónomos', 'Diseñadores, programadores, fotógrafos, traductores, técnicos… que trabajan solos se agrupan para compartir gestoría, herramientas, comercialización, espacios y determinados servicios.', 'trabajo', 'Calle de Piamonte 12, Chueca, Madrid', 'Chueca', 'Calle de Piamonte 12', 40.4235, -3.6958, 'dinero', 'buscando', 22, 0, '', '', 'Grupo mínimo de autónomos y acuerdo sobre qué servicios se comparten', 'Servicios compartidos (gestoría, herramientas, espacio) a menor coste individual', 'Cuota o aportación, tiempo de coordinación y perfiles profesionales diversos', 'Servicios para autónomos', owner_id, '2026-08-02T10:20:00.000Z'),
  ('a0000000-0000-4000-8000-000000000130', 'Bolsa de proyectos entre profesionales', 'Una persona consigue un trabajo que requiere tres especialidades y, en lugar de rechazarlo, encuentra dentro de Appoyo Mutuo a las otras dos personas necesarias.

Puede ser una fábrica de nuevas cooperativas: primero colaboran en proyectos y después descubren que trabajar juntos tiene sentido.', 'trabajo', 'Calle de Argensola 8, Justicia, Madrid', 'Justicia', 'Calle de Argensola 8', 40.4258, -3.6935, 'conocimiento', 'buscando', 30, 0, '', '', 'Perfiles visibles y reglas claras de colaboración y cobro', 'Equipos temporales para encargos y posibles cooperativas nacidas de la práctica', 'Profesionales de distintas especialidades y un canal para publicar encargos', 'Bolsa de proyectos', owner_id, '2026-08-02T10:25:00.000Z'),
  ('a0000000-0000-4000-8000-000000000131', 'Red de acompañamiento a citas y gestiones', 'Personas que necesitan acompañamiento para ir al médico, hacer trámites o acudir a una oficina pública pueden encontrar personas dispuestas a acompañarlas.

Es una necesidad cotidiana que hoy suele recaer solo sobre familiares.', 'cuidados', 'Calle de O''Donnell 50, Retiro, Madrid', 'Retiro', 'Calle de O''Donnell 50', 40.4205, -3.6728, 'tiempo', 'buscando', 24, 0, '', '', 'Disponibilidad puntual y acuerdos claros sobre qué incluye el acompañamiento', 'Citas y trámites cubiertos con compañía vecinal', 'Tiempo flexible y personas que ofrecen o necesitan acompañamiento', 'Acompañamiento a gestiones', owner_id, '2026-08-02T10:30:00.000Z'),
  ('a0000000-0000-4000-8000-000000000132', 'Red de descanso para cuidadores', 'Personas que cuidan habitualmente a familiares pueden coordinarse para disponer de algunas horas libres mediante una red de apoyo.

Hay que diseñar con cuidado los límites legales y de responsabilidad; como necesidad social es enorme.', 'cuidados', 'Calle de Albufera 80, Vallecas, Madrid', 'Vallecas', 'Avenida de la Albufera 80', 40.3912, -3.6585, 'tiempo', 'buscando', 20, 0, '', '', 'Protocolo de relevos, límites claros y formación básica (no sustituye cuidados profesionales)', 'Horas de respiro para cuidadores mediante relevos vecinales acordados', 'Tiempo de relevo, confianza y reglas compartidas de responsabilidad', 'Descanso de cuidadores', owner_id, '2026-08-02T10:35:00.000Z'),
  ('a0000000-0000-4000-8000-000000000133', 'Biblioteca de objetos y conocimientos', 'No solo prestar libros: herramientas, instrumentos musicales, material audiovisual, máquinas de coser, material educativo… asociados a personas que saben utilizarlos.

«Tengo una impresora 3D y sé usarla» / «Quiero aprender a utilizar una.»', 'educacion', 'Calle de Argumosa 16, Lavapiés, Madrid', 'Lavapiés', 'Calle de Argumosa 16', 40.4085, -3.6995, 'conocimiento', 'buscando', 28, 0, '', '', 'Inventario inicial y personas dispuestas a prestar y enseñar el uso', 'Préstamo de objetos + aprendizaje asociado a quien los conoce', 'Objetos, saberes y un espacio o sistema de préstamo', 'Biblioteca de objetos y saberes', owner_id, '2026-08-02T10:40:00.000Z'),
  ('a0000000-0000-4000-8000-000000000134', 'Academia comunitaria de preparación laboral', 'Personas con experiencia ayudan a otras a preparar entrevistas, CV, oposiciones, idiomas, herramientas digitales o habilidades profesionales.

Puede funcionar mediante intercambio de tiempo.', 'educacion', 'Calle de Embajadores 55, Lavapiés, Madrid', 'Lavapiés', 'Calle de Embajadores 55', 40.4062, -3.7022, 'conocimiento', 'buscando', 22, 0, '', '', 'Mentoras/es disponibles y un formato de sesiones (presencial o mixto)', 'Sesiones de preparación laboral entre pares, con o sin intercambio de horas', 'Experiencia profesional, tiempo y un espacio o canal de citas', 'Preparación laboral', owner_id, '2026-08-02T10:45:00.000Z'),
  ('a0000000-0000-4000-8000-000000000135', 'Red de acompañamiento para salir del sedentarismo', 'No es un grupo de fitness: es algo más cotidiano.

«Quiero caminar tres tardes a la semana pero sola nunca lo hago.» La plataforma encuentra personas cercanas con el mismo objetivo y crea grupos pequeños.', 'salud', 'Parque de El Capricho, Barajas, Madrid', 'Barajas', 'Paseo de la Alameda de Osuna', 40.4565, -3.5985, 'tiempo', 'buscando', 18, 0, '', '', 'Grupos pequeños con horarios fijos y sin promesas médicas', 'Paseos o actividad ligera en compañía, de forma regular', 'Tiempo, cercanía geográfica y ganas de constancia compartida', 'Salir del sedentarismo', owner_id, '2026-08-02T10:50:00.000Z'),
  ('a0000000-0000-4000-8000-000000000136', 'Grupos comunitarios para combatir la soledad', 'No como terapia, sino como infraestructura social: comidas, paseos, juegos, conversaciones, excursiones y actividades para personas que viven solas.

Puede ser una de las piezas más importantes de Appoyo Mutuo.', 'salud', 'Plaza de Chamberí, Madrid', 'Chamberí', 'Plaza de Chamberí', 40.4345, -3.6978, 'tiempo', 'buscando', 25, 0, '', '', 'Actividades regulares y reglas de convivencia (no sustituye atención sanitaria)', 'Agenda compartida de encuentros que rompen el aislamiento', 'Tiempo, un punto de encuentro y personas que quieran participar', 'Contra la soledad', owner_id, '2026-08-02T10:55:00.000Z'),
  ('a0000000-0000-4000-8000-000000000137', 'Espacio creativo compartido', 'Personas que quieren pintar, hacer cerámica, fotografía, bricolaje, impresión 3D, etc. juntan demanda suficiente para alquilar y equipar un espacio.

«No podía permitirme un taller.» «Tú tampoco.» «Y otras 12 personas tampoco.» = Tenemos un taller.', 'ocio', 'Calle del Reloj 4, Centro, Madrid', 'Centro', 'Calle del Reloj 4', 40.4188, -3.7095, 'dinero', 'buscando', 14, 0, '', '', 'Grupo suficiente para cubrir alquiler y equipamiento básico', 'Taller compartido con turnos y materiales comunes', 'Aportación económica, tiempo de uso y gestión del espacio', 'Espacio creativo', owner_id, '2026-08-02T11:00:00.000Z'),
  ('a0000000-0000-4000-8000-000000000138', 'Viajes y escapadas colectivas', 'Personas interesadas en una ruta, viaje, acampada o actividad reúnen un grupo y comparten transporte, alojamiento y organización.

No hace falta una empresa detrás: primero aparece la necesidad colectiva y después se organiza la solución, respetando las obligaciones legales que correspondan.', 'ocio', 'Estación de Atocha, Madrid', 'Atocha', 'Plaza del Emperador Carlos V', 40.4065, -3.6895, 'tiempo', 'buscando', 16, 0, '', '', 'Grupo mínimo, presupuesto compartido y acuerdo de organización', 'Escapadas y rutas organizadas entre particulares de forma colectiva', 'Personas interesadas, tiempo de organización y recursos para transporte/alojamiento', 'Escapadas colectivas', owner_id, '2026-08-02T11:05:00.000Z')
  on conflict (id) do update set created_by = excluded.created_by;
end $$;
